Started kickoff of the project
wolox-training/nv-angular pull request #1
Opened 2018-10-17 17:00 UTC by nvescio

Summary
[Change!] Describe your feature, problems you had, notes, improvements and others.

Screenshots
Chrome
[Change!] Show the screenshots of the views you modified.

Trello Card
[Change!] Link to the associated Trello card.

2018-10-17 18:46 UTC, CarlosHWolox commented on training_maquetado/index.html
> +</html>
We usually leave an empty line at the end of the file so this icon do not appear on github

2018-10-17 18:46 UTC, CarlosHWolox commented on training_maquetado/index.html
> +    <img class="triangle" src="assets/triangle.svg">
Use a more descriptive name for classes

2018-10-17 18:46 UTC, CarlosHWolox commented on training_maquetado/scss/titles.scss
> +    display:flex;
space

2018-10-17 18:46 UTC, CarlosHWolox commented on training_maquetado/scss/titles.scss
> +    padding-left: $title-decoration-width - 20px;
i think this variable here is unnecesary

2018-10-18 17:09 UTC, CarlosHWolox approved these changes

2018-10-18 19:27 UTC, FrankIglesias requested changes

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/.gitignore
> +.DS_Store
add tailing line

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/colors.scss
> +$grey: #C4C4C4;
same

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/equalizer.scss
> +
delete extra spaces

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +.tech-container {
indentation

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +
delete this two empty lines

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/titles.scss
> +.triangle {
check indentation

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/titles.scss
> +    height: $title-decoration-height;
set only width as fixed

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/index.html
> +
delete line

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/index.html
> +  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
change this one for roboto

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/index.html
> +
delete line

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/index.html
> +  <div class="title-container">
remove this div  and change it for a h1 instead

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/index.html
> +    <img class="triangle" src="assets/triangle.svg">
add an alt

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/index.html
> +
remove this line

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/index.html
> +  <div class="tech-container">
check indentation

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/index.html
> +        <img class="tech-icon" src="assets/react_icon.svg">
add an alt

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/styles.scss
> +$text-small: 12px;
add empty line at the bottom of the file

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/styles.scss
> +$roboto: 'Roboto', sans-serif;
are you using this variable?

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +.tech-container,
I'd do something like
```scss 
.tech-container {
...

  &::before {
     ....
   }
```

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +.tech-container:before {
join this with the `&::before`

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +    display: block;
this is unnecessary

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +    position: absolute;
this is not neccesary

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +.tech-icon {
check indentation

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +    width: $tech-logo-size;
fix only width or margin not both

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/titles.scss
> +    position: absolute;
You dont need this

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/titles.scss
> +    font-family: $roboto;
move this prop to an upper element I'd use `*` or `body`

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/index.html
> +        <h2 class="tech-release">Release: 2013</h2>
this should be a less important headline like 3 or 4

2018-10-18 19:27 UTC, FrankIglesias commented on training_maquetado/scss/styles.scss
> +$roboto: 'Roboto', sans-serif;
This file should be renamed for constants

2018-10-22 14:09 UTC, FrankIglesias requested changes

2018-10-22 14:09 UTC, FrankIglesias commented on training_maquetado/scss/titles.scss
> +    &::before {
leave an empty line  before the `&::before`

2018-10-22 14:09 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +    &,
same

2018-10-22 14:09 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +    &::before {
same

2018-10-22 16:36 UTC, FrankIglesias approved these changes

2018-10-22 17:17 UTC, merged