Content layout created
wolox-training/nv-angular pull request #2
Opened 2018-10-18 19:49 UTC by nvescio

Summary
 - Content layout

Screenshots
Chrome
![contentlayout](https://user-images.githubusercontent.com/44203749/47179769-4a4a3d80-d2f5-11e8-809b-e522262aa21b.png)

Trello Card
https://trello.com/c/mMQAobZb/23-content-layout

2018-10-22 14:23 UTC, CarlosHWolox commented on training_maquetado/index.html
> +          <img class="tech-icon" src="assets/react_icon.svg">
indentation

2018-10-22 14:23 UTC, CarlosHWolox commented on training_maquetado/index.html
> +          <img class="tech-icon" src="assets/rails_icon.png">
indentation

2018-10-22 19:37 UTC, CarlosHWolox commented on training_maquetado/scss/tech.scss
> +      margin: 2% 0;
Try not to use percent and use px values

2018-10-22 19:37 UTC, CarlosHWolox commented on training_maquetado/scss/tech.scss
> +  height: 350px;
you can define a min-height value

2018-10-22 19:37 UTC, CarlosHWolox commented on training_maquetado/scss/tech.scss
> +  padding: 12px 12px;
you can center the content with align-content so you dont need this paddings

2018-10-22 19:37 UTC, CarlosHWolox commented on training_maquetado/scss/tech.scss
>    position: relative;
i think this is not necessary

2018-10-22 19:37 UTC, CarlosHWolox commented on training_maquetado/scss/tech.scss
> +  width: 55%;
Using percent is not necessary, with just margin, padding and width you can center the elements

2018-10-22 19:37 UTC, CarlosHWolox commented on training_maquetado/scss/titles.scss
> +    &,
&, &::before?

2018-10-22 19:37 UTC, CarlosHWolox commented on training_maquetado/scss/titles.scss
> +        padding: 5% 20%;
percent is not necessary, use top or margin on the title root class

2018-10-24 00:14 UTC, FrankIglesias requested changes

2018-10-24 00:14 UTC, FrankIglesias commented on training_maquetado/index.html
> +      <img class="tech-icon" alt="ReactJS icon" src="assets/react_icon.svg">
add a slash before the >

2018-10-24 00:14 UTC, FrankIglesias commented on training_maquetado/index.html
> +      <img class="tech-icon" src="assets/angular_icon.svg">
add a slash before the > and an alt

2018-10-24 00:14 UTC, FrankIglesias commented on training_maquetado/index.html
> +      <img class="tech-icon" src="assets/vue_icon.svg">
add a slash before the > and an alt

2018-10-24 00:14 UTC, FrankIglesias commented on training_maquetado/index.html
> +      <img class="tech-icon" src="assets/elm_icon.svg">
add a slash before the > and an alt

2018-10-24 00:14 UTC, FrankIglesias commented on training_maquetado/index.html
> +      <img class="tech-icon" src="assets/rails_icon.png">
add a slash before the > and an alt

2018-10-24 00:14 UTC, FrankIglesias commented on training_maquetado/index.html
> +      <img class="tech-icon" src="assets/express_icon.svg">
add a slash before the > and an alt

2018-10-24 00:14 UTC, FrankIglesias commented on training_maquetado/index.html
> +      <img class="tech-icon" src="assets/aspnet_icon.png">
add a slash before the > and an alt

2018-10-24 00:14 UTC, FrankIglesias commented on training_maquetado/index.html
> +      <img class="tech-icon" src="assets/django_icon.svg">
add a slash before the > and an alt

2018-10-24 00:14 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +//   padding: 12px 12px;
remove commented line

2018-10-24 00:14 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +  min-height: 350px;
I think this is a height value

2018-10-24 13:34 UTC, CarlosHWolox approved these changes

2018-10-24 13:34 UTC, CarlosHWolox commented on training_maquetado/scss/tech.scss
> +//   padding: 12px 12px;
Delete comment

2018-10-24 14:42 UTC, FrankIglesias requested changes

2018-10-24 14:42 UTC, FrankIglesias commented on training_maquetado/scss/titles.scss
> +  margin: 0 325px;
This can be raplaced by a flex prop

2018-10-24 22:38 UTC, FrankIglesias approved these changes

2018-10-25 11:25 UTC, merged