Transition feature
wolox-training/nv-angular pull request #3
Opened 2018-10-18 19:55 UTC by nvescio

Summary
 - Transition added to all technologies

Screenshots
Chrome
![transition-1](https://user-images.githubusercontent.com/44203749/47180213-68fd0400-d2f6-11e8-87de-3dff4d334f4b.png)
![transition-2](https://user-images.githubusercontent.com/44203749/47180216-6a2e3100-d2f6-11e8-98d9-c132c57b311c.png)

Trello Card
https://trello.com/c/N9uksGkU/25-css-transitions

2018-10-22 20:23 UTC, CarlosHWolox commented on training_maquetado/scss/tech.scss
> +.tech-container::before {
use & inside class, you also repeated the  :before

2018-10-22 20:23 UTC, CarlosHWolox commented on training_maquetado/scss/tech.scss
> +.tech-container:hover::before {
same as above

2018-10-24 22:39 UTC, FrankIglesias requested changes

2018-10-24 22:39 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +    margin: 0 350px 80px;
I think this is not needed

2018-10-24 22:39 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +      &:hover::before {
check indentation

2018-10-24 22:39 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +
remove spaces

2018-10-25 15:26 UTC, FrankIglesias requested changes

2018-10-25 15:26 UTC, FrankIglesias commented on training_maquetado/scss/tech.scss
> +
Delete space

2018-10-25 15:27 UTC, FrankIglesias approved these changes

2018-10-25 15:27 UTC, merged