Navbar added
wolox-training/nv-angular pull request #4
Opened 2018-10-18 19:57 UTC by nvescio

Summary
 - Navbar

Screenshots
Chrome
![navbar](https://user-images.githubusercontent.com/44203749/47180344-c2fdc980-d2f6-11e8-8457-18691a47dce2.png)

Trello Card
https://trello.com/c/8JUcMnuT/13-navbar

2018-10-22 20:33 UTC, CarlosHWolox commented on training_maquetado/index.html
> +  <div class="navbar-container">
you can use the header tag

2018-10-22 20:33 UTC, CarlosHWolox commented on training_maquetado/scss/navbar.scss
> +  box-shadow: 2px 4px 8px silver;
use a scss color variable

2018-10-22 20:33 UTC, CarlosHWolox commented on training_maquetado/scss/navbar.scss
> +  overflow: hidden;
why the overflow?

2018-10-22 20:33 UTC, CarlosHWolox commented on training_maquetado/scss/navbar.scss
> +  padding: 0 15%;
use pxs

2018-10-22 20:33 UTC, CarlosHWolox commented on training_maquetado/scss/navbar.scss
> +  top: 0;
Is this necessary?

2018-10-22 20:33 UTC, CarlosHWolox commented on training_maquetado/index.html
> +    <h1 class="navbar-title">Developer Tools</h1>
Use h1 just for important or destacable content, for SEO reasons try to keep as low and descriptive as possible your h1 tags, as you already has used h1 for the titles use another one for this.

2018-10-22 20:33 UTC, CarlosHWolox commented on training_maquetado/scss/navbar.scss
> +  font-family: $roboto;
I think you can define all the font-family on the styles-scss so you dont have to set it like this.

2018-10-24 22:41 UTC, FrankIglesias requested changes

2018-10-24 22:41 UTC, FrankIglesias commented on training_maquetado/index.html
> +
remove line

2018-10-25 17:09 UTC, FrankIglesias approved these changes

2018-10-25 17:11 UTC, merged