Footer added
wolox-training/nv-angular pull request #5
Opened 2018-10-18 19:59 UTC by nvescio

Summary

 - Footer

Screenshots
Chrome
![footer](https://user-images.githubusercontent.com/44203749/47180482-1243fa00-d2f7-11e8-932b-66347900902f.png)

Trello Card
https://trello.com/c/z65SGK2B/14-footer

2018-10-22 20:37 UTC, CarlosHWolox commented on training_maquetado/index.html
> +  <div class="footer-container">
you can use the footer tag

2018-10-22 20:37 UTC, CarlosHWolox commented on training_maquetado/index.html
> +    <img class="logo-white" src="assets/wolox_logo_white.svg">
use alt text

2018-10-22 20:37 UTC, CarlosHWolox commented on training_maquetado/index.html
> +    <h6 class="copyright-text">Copyright 2018. Wolox. All rights reserved.</h6>
i wpould ise a p as it is not relevant info for seo spiders

2018-10-22 20:37 UTC, CarlosHWolox commented on training_maquetado/scss/footer.scss
> +  padding: 2% 15% 1%;
use px

2018-10-22 20:37 UTC, CarlosHWolox commented on training_maquetado/scss/footer.scss
> +  width: 100%;
i think this is unnecessary

2018-10-22 20:37 UTC, CarlosHWolox commented on training_maquetado/scss/footer.scss
> +}
Enter

2018-10-22 20:37 UTC, CarlosHWolox commented on training_maquetado/scss/footer.scss
> +
I would define a min-width for the image

2018-10-25 15:20 UTC, FrankIglesias requested changes

2018-10-25 15:20 UTC, FrankIglesias commented on training_maquetado/index.html
> +
Remove this line

2018-10-25 15:20 UTC, FrankIglesias commented on training_maquetado/scss/footer.scss
> +  color: white;
use color variables

2018-10-25 17:10 UTC, FrankIglesias requested changes

2018-10-25 17:10 UTC, FrankIglesias commented on training_maquetado/scss/colors.scss
> +$white: #FFFFFF;
this should be  written like #FFF

2018-10-25 17:15 UTC, FrankIglesias approved these changes

2018-10-25 17:20 UTC, merged